package interfaces

const (
	ERROR_INTERNAL_SERVER            = 100
	INVALID_NUMBER_FROM_TOKEN        = 101
	ERROR_INVALID_INPUT              = 102
	ERROR_CONNECTION_NOT_FOUND       = 103
	ERROR_CONNECTION_NOT_INITIALIZED = 104
	ERROR_CONNECTION_LOGGED_OUT      = 105
	ERROR_TOKEN_NOT_PASSED           = 106
	ERROR_INVALID_TOKEN              = 107
)
